### ISSUE TITLE
Errors in app

### ISSUE THREAD

**Issue by jagrunberg** [TangoChen/Coloreality#7]
I had recently created the Coloreality app for my testing using the example project given, once I loaded it up to my phone, I started the PC application, typed in the right information, but my phone doesn't connect, it says "Error: Failed to connect within the last 5 seconds." How do I fix this error, is it even something on my end. My phone and PC are connected to the same network and I don't see anything that can create a conflict.

**Comment by TangoChen** [comment]
Hi, here're several things you can check to ensure the server and the phone app should be able to connect together:

- Did you click _Start Server_ first on PC application before tapping _Connect_ on the phone?

- Is the PC application allowed to access network by your computer firewall or any security softwares? -Usually when I first start the PC application, my computer pop up a dialog to ask if I allow it to access networks, I simply click Allow. Otherwise, if it's blocked to access network, it won't be able to create a network server to be reached out by your phones.

- Similar to the above one, is the Coloreality phone app allowed to access network? -Tap _Allow_ when there's a system alert or change its setting in the setting app.

- The right information you mentioned: The phone app should have both correct IP and Port of the PC server.

Let me know if you are able to connect them later.

Thank you,
TC

**Comment by jagrunberg** [comment]
So i found the issue to be with the pc application, i had all my settings correct on both my pc and phone, the issue was that on first run of the pc application, the default ip address is wrong, you will have to boot the application at least twice to get the proper ip configuration. Thank you for your time.
